import type { Metadata } from "next";
import { Amiko } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from "sonner";
const amiko = Amiko({ subsets: ["latin"] , weight : '400'});

export const metadata: Metadata = {
  title: "Basic web wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={amiko.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
            <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
